typography_spectrum: 0.6006
color:
  brandColors:
    - '#006a9d'
    - '#f75256'
    - '#ffd66a'
    - '#ffffff'
    - '#718792'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49116
analytics:
  google: null
  facebook: null
  twitter: null
name: fo
cta:
  domain: null
  bucket: null
  version: null
style: 'https://forresto.github.io/nilla-system/nilla.js'
favicon: null
title: Forrest O
description: testing stuff
purpose: []
