name: Fo
favicon: null
layout_spectrum: 0.49116
typography_spectrum: 0.6006
style: 'https://forresto.github.io/nilla-system/nilla.js'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006a9d'
    - '#f75256'
    - '#ffd66a'
    - '#ffffff'
    - '#718792'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
