analytics: {}
color:
  brandColors:
    - '#006a9d'
    - '#f75256'
    - '#ffd66a'
    - '#ffffff'
    - '#718792'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.66791
name: Fo
opengraph: {}
purpose: []
typography_spectrum: 0.82346
